[12:40 PM] Ashwin Kumar Maheswaran
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

USER app

WORKDIR /app

EXPOSE 8080

EXPOSE 8081
 
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

ARG BUILD_CONFIGURATION=Release

WORKDIR /src

COPY ["JenkinsDemo.csproj", "."]

RUN dotnet restore "./././JenkinsDemo.csproj"

COPY . .

WORKDIR "/src/."

RUN dotnet build "./JenkinsDemo.csproj" -c $BUILD_CONFIGURATION -o /app/build
 
FROM build AS publish

ARG BUILD_CONFIGURATION=Release

RUN dotnet publish "./JenkinsDemo.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false
 
FROM base AS final

WORKDIR /app

COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "PracticeJenkins.dll"]